[package]
name = "continuous"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argmin = { version = "0.9.0" }
argmin-math = { version = "0.3.0" }
rand = "0.8.5"

